'use strict';
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const api = window.hoyo;
let state={settings:{},mods:[],presets:[],runtime:{}}, categories=[], category='', page=1, query='', total=0, busyCount=0, progressRevision=0, browseRevision=0;
const titles={workshop:['角色工坊','从 GameBanana 浏览并安装角色模组'],library:['我的模组','管理本机已安装的模组'],presets:['搭配方案','保存并切换整套角色搭配'],settings:['设置','配置 XXMI、模组目录与更新偏好']};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeImage=u=>{try{const x=new URL(u);return x.protocol==='https:'&&(x.hostname==='gamebanana.com'||x.hostname.endsWith('.gamebanana.com'))?x.href:''}catch{return''}};
const formatDate=v=>{if(!v)return'';const raw=typeof v==='string'&&/^\d+$/.test(v)?Number(v):v;const d=new Date(typeof raw==='number'&&raw<1e12?raw*1000:raw);return Number.isNaN(d.valueOf())?'':new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'short',day:'numeric'}).format(d)};
const formatSize=n=>{n=Number(n)||0;return n>1048576?(n/1048576).toFixed(1)+' MB':n>1024?Math.round(n/1024)+' KB':n+' B'};

function notice(message,error=false){const n=$('#notice');n.textContent=message;n.className='notice'+(error?' error':'');n.hidden=!message;if(message)setTimeout(()=>{if(n.textContent===message)n.hidden=true},6500)}
function setBusy(value){busyCount=Math.max(0,busyCount+(value?1:-1));const locked=busyCount>0;$$('button').filter(el=>!el.closest('nav')&&!el.classList.contains('category')&&!el.closest('.pager')).forEach(el=>el.disabled=locked)}
async function call(action,payload,opts={reload:false}){if(!api?.call)throw new Error('本地服务不可用，请重新启动应用。');setBusy(true);try{const result=await api.call(action,payload);if(opts.reload)await loadState();return result}catch(e){notice(e?.message||String(e),true);throw e}finally{setBusy(false)}}
async function loadState(){state=await api.call('state');renderState()}
function renderState(){state.settings??={};state.mods??=[];state.presets??=[];$('#platform-label').textContent=state.runtime?.platform?`${state.runtime.platform} · 本地就绪`:'本地服务已连接';$('#xxmi-path').textContent=state.settings.xxmiPath||'尚未选择';$('#mods-path').textContent=state.settings.modsPath||'尚未选择';$('#data-root').textContent=state.runtime?.dataRoot?`数据目录：${state.runtime.dataRoot}`:'数据目录不可用';$('#auto-enable').checked=!!state.settings.autoEnable;$('#auto-update').checked=!!state.settings.autoUpdate;$('#onboarding').hidden=!!(state.settings.xxmiPath&&state.settings.modsPath);renderLibrary();renderPresets()}
function imageMarkup(url,alt){const safe=safeImage(url);return safe?`<img src="${esc(safe)}" alt="${esc(alt)}" loading="lazy">`:'<div class="preview-placeholder">暂无预览</div>'}
function renderLibrary(){const box=$('#library-grid'),empty=$('#library-empty');box.innerHTML='';empty.hidden=state.mods.length>0;empty.innerHTML='<strong>还没有本机模组</strong>从角色工坊安装，或导入 ZIP、7Z、RAR 文件。';for(const m of state.mods){const el=document.createElement('article');el.className='library-item';el.dataset.testid='installed-mod';el.innerHTML=`<div class="library-thumb">${imageMarkup(m.preview,m.name)}</div><div><div class="eyebrow">${esc(m.characterName)}</div><h3>${esc(m.name)}</h3><p class="meta">${esc(m.author||'本地导入')} · ${m.active?'<span class="active-badge">● 已启用</span>':'<span class="active-badge inactive-badge">未启用</span>'}</p></div><div class="item-actions"><button class="button secondary toggle">${m.active?'停用':'启用'}</button>${m.sourceId?'<button class="link-button source">来源</button>':''}<button class="button danger remove">移除</button></div>`;$('.toggle',el).onclick=()=>mutate(m.active?'disable':'enable',{id:m.id});$('.remove',el).onclick=()=>confirmRemove(m);$('.source',el)?.addEventListener('click',()=>call('openSource',{id:Number(m.sourceId)}).catch(()=>{}));box.append(el)}}
function renderPresets(){const box=$('#preset-grid'),empty=$('#preset-empty');box.innerHTML='';empty.hidden=state.presets.length>0;empty.innerHTML='<strong>还没有搭配方案</strong>先在“我的模组”启用喜欢的组合，再保存为方案。';for(const p of state.presets){const names=(p.modIds||[]).map(id=>state.mods.find(m=>m.id===id)).filter(Boolean).map(m=>m.characterName+' · '+m.name);const el=document.createElement('article');el.className='preset-item';el.innerHTML=`<div><h3>${esc(p.name)}</h3><p>${names.length?esc(names.join('、')):'空搭配 · 将停用所有模组'}</p></div><div class="item-actions"><button class="button primary apply">应用</button><button class="button danger delete">删除</button></div>`;$('.apply',el).onclick=()=>mutate('applyPreset',{id:p.id});$('.delete',el).onclick=()=>confirmDeletePreset(p);box.append(el)}}
async function mutate(action,payload){try{return await call(action,payload,{reload:true})}catch{return null}}
function showPage(name){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+name));[$('#page-title').textContent,$('#page-subtitle').textContent]=titles[name]}
function renderCategories(){const box=$('#category-list'),filter=($('#character-search')?.value||'').trim().toLocaleLowerCase();box.innerHTML='';for(const c of categories.filter(x=>!filter||String(x.name).toLocaleLowerCase().includes(filter))){const b=document.createElement('button');b.className='category'+(String(c.id)===String(category)?' active':'');const icon=safeImage(c.icon);if(icon){const img=document.createElement('img');img.src=icon;img.alt='';b.append(img)}const name=document.createElement('span');name.className='category-name';name.textContent=c.name;b.append(name);b.onclick=()=>{category=c.id;page=1;renderCategories();browse()};box.append(b)}}
async function loadCategories(){try{categories=await call('categories');if(!category&&categories.length)category=categories[0].id;renderCategories();await browse()}catch{$('#browse-empty').hidden=false;$('#browse-empty').innerHTML='<strong>角色列表暂时不可用</strong>请检查网络后点击右上角“刷新”；本地模组仍可正常管理。'}}
async function browse(){
  const revision=++browseRevision,grid=$('#browse-grid'),empty=$('#browse-empty');
  grid.innerHTML='';empty.hidden=true;
  if(!category){empty.hidden=false;empty.innerHTML='<strong>没有可浏览的角色分类</strong>请稍后重试，或在“我的模组”中导入本地压缩包。';return;}
  try{
    const r=await api.call('browse',{category,page,query});
    if(revision!==browseRevision)return;
    total=Number(r.total)||0;page=Number(r.page)||page;
    grid.replaceChildren(...(r.records||[]).map(workshopCard));
    empty.hidden=grid.children.length>0;
    if(!empty.hidden)empty.innerHTML='<strong>没有找到模组</strong>试试其他角色或搜索词。';
    $('#page-info').textContent=`第 ${page} 页${total?' · 共 '+total+' 个':''}`;
    $('#prev-page').disabled=page<=1;$('#next-page').disabled=!r.records?.length||page*20>=total;
  }catch(e){if(revision!==browseRevision)return;notice(e.message,true);empty.hidden=false;empty.innerHTML='<strong>加载失败</strong>请检查网络后重试。';}
}
function workshopCard(m){const el=document.createElement('article');el.className='mod-card';el.dataset.testid='browse-card';el.innerHTML=`<div class="preview">${imageMarkup(m.preview,m.name)}</div><div class="mod-card-body"><div class="eyebrow">${esc(m.characterName||categories.find(c=>String(c.id)===String(category))?.name||'角色模组')}</div><h3 title="${esc(m.name)}">${esc(m.name)}</h3><p class="meta">${esc(m.author||'未知作者')}${m.updatedAt?' · '+esc(formatDate(m.updatedAt)):''}</p><div class="card-actions"><button class="link-button source">在 GameBanana 查看</button><button class="button primary detail">查看详情</button></div></div>`;$('.source',el).onclick=()=>call('openSource',{id:Number(m.id)}).catch(()=>{});$('.detail',el).onclick=()=>openDetail(m);return el}
function modal(title,subtitle,body,actions){$('#modal-title').textContent=title;$('#modal-subtitle').textContent=subtitle||'';$('#modal-body').innerHTML=body;$('#modal-actions').innerHTML=actions;$('#modal').showModal()}
function closeModal(){if($('#modal').open)$('#modal').close()}
async function openDetail(record){try{const d=await call('detail',{id:record.id});const imgs=(d.images||[]).map(u=>safeImage(u)).filter(Boolean).map(u=>`<img src="${esc(u)}" alt="模组预览" loading="lazy">`).join('');const files=d.files||[];modal(d.name,`${d.author||'未知作者'} · ${d.characterName||'请选择角色'}`,`<p class="description">${esc(d.description||'作者没有填写说明。')}</p>${imgs?`<div class="detail-images">${imgs}</div>`:''}<div class="field"><label>选择要安装的文件</label><div>${files.length?files.map((f,i)=>`<label class="file-option"><input type="radio" name="file" value="${esc(f.id)}" ${files.length===1?'checked':''}><span><strong>${esc(f.name)}</strong><small>${esc(formatSize(f.size))}</small></span></label>`).join(''):'没有可下载的文件'}</div></div><div id="character-fields"></div>`,`<button class="button secondary" value="cancel">取消</button><button type="button" class="button primary" id="install-confirm" ${files.length?'':'disabled'}>下载并安装</button>`);const supplied=d.characterId||record.characterId||category;const known=categories.find(c=>String(c.id)===String(supplied));if(!known){$('#character-fields').innerHTML=`<div class="field"><label for="detail-character">角色归属（必选）</label><select id="detail-character"><option value="">请选择角色</option>${categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}<option value="__custom">其他角色…</option></select></div><div class="field" id="custom-character-field" hidden><label for="custom-character">角色名称</label><input id="custom-character" maxlength="40"></div>`;$('#detail-character').onchange=e=>$('#custom-character-field').hidden=e.target.value!=='__custom'}$('#install-confirm').onclick=async()=>{const fileId=$('input[name=file]:checked')?.value;if(!fileId)return notice('请选择一个安装文件。',true);let characterId=known?String(known.id):'',characterName=known?.name;if(!known){const selected=$('#detail-character').value;if(!selected)return notice('请选择角色归属。',true);if(selected==='__custom'){characterName=$('#custom-character').value.trim();if(!characterName)return notice('请输入角色名称。',true);characterId='local:'+characterName}else{const c=categories.find(x=>String(x.id)===selected);characterId=String(c.id);characterName=c.name}}closeModal();try{await call('install',{sourceId:d.id,fileId,characterId,characterName},{reload:true});notice('模组安装完成。')}catch{}}}catch{}}
function chooseCharacter(title,onConfirm){modal(title,'请选择该模组所属角色。',`<div class="field"><label for="character-select">角色</label><select id="character-select"><option value="">请选择</option>${categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}<option value="__custom">其他角色…</option></select></div><div class="field" id="import-custom-field" hidden><label for="import-custom">角色名称</label><input id="import-custom" maxlength="40" placeholder="例如：旅行者"></div>`,`<button class="button secondary" value="cancel">取消</button><button type="button" class="button primary" id="character-confirm">继续</button>`);$('#character-select').onchange=e=>$('#import-custom-field').hidden=e.target.value!=='__custom';$('#character-confirm').onclick=()=>{const id=$('#character-select').value;if(!id)return notice('请选择角色。',true);let name;if(id==='__custom'){name=$('#import-custom').value.trim();if(!name)return notice('请输入角色名称。',true)}else name=categories.find(c=>String(c.id)===id)?.name;closeModal();onConfirm({characterId:id==='__custom'?'local:'+name:String(id),characterName:name})}}
function confirmRemove(m){modal('移除模组','此操作会删除本机保存的模组文件。',`<p>确定移除“${esc(m.name)}”吗？相关搭配方案也会更新。</p>`,`<button class="button secondary" value="cancel">取消</button><button type="button" class="button danger" id="remove-confirm">确认移除</button>`);$('#remove-confirm').onclick=()=>{closeModal();mutate('remove',{id:m.id})}}
function confirmDeletePreset(p){modal('删除搭配方案','不会删除其中的模组。',`<p>确定删除“${esc(p.name)}”吗？</p>`,`<button class="button secondary" value="cancel">取消</button><button type="button" class="button danger" id="delete-confirm">确认删除</button>`);$('#delete-confirm').onclick=()=>{closeModal();mutate('deletePreset',{id:p.id})}}
function savePreset(){modal('保存当前搭配','记录现在启用的所有角色模组。',`<div class="field"><label for="preset-name">方案名称</label><input id="preset-name" maxlength="50" autofocus placeholder="例如：日常探索"></div>`,`<button class="button secondary" value="cancel">取消</button><button type="button" class="button primary" id="preset-confirm">保存</button>`);$('#preset-confirm').onclick=()=>{const name=$('#preset-name').value.trim();if(!name)return notice('请输入方案名称。',true);closeModal();mutate('savePreset',{name})}}
async function checkUpdates(){try{const updates=await call('checkUpdates');if(!updates.length)return notice('所有模组均为最新版本。');modal('可用更新',`找到 ${updates.length} 个更新。`,`<div class="updates">${updates.map((u,i)=>`<div class="update-row"><div><strong>${esc(u.name)}</strong><div class="meta">${u.automatic?'可使用同名文件更新':'请选择更新文件'}</div></div><select data-update="${i}" aria-label="${esc(u.name)} 的更新文件"><option value="">暂不更新</option>${(u.files||[]).map(f=>`<option value="${esc(f.id)}">${esc(f.name)}</option>`).join('')}</select></div>`).join('')}</div>`,`<button class="button secondary" value="cancel">稍后</button><button type="button" class="button primary" id="update-confirm">安装所选更新</button>`);$('#update-confirm').onclick=async()=>{const choices=$$('[data-update]').map(s=>({u:updates[Number(s.dataset.update)],fileId:s.value})).filter(x=>x.fileId);if(!choices.length)return notice('请选择至少一个更新文件。',true);closeModal();for(const x of choices){try{await call('updateMod',{id:x.u.id,fileId:x.fileId},{reload:true})}catch{return}}notice('所选模组已更新。')}}catch{}}

$$('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#character-search').oninput=renderCategories;$('#search-button').onclick=()=>{query=$('#search-input').value.trim();page=1;browse()};$('#search-input').onkeydown=e=>{if(e.key==='Enter')$('#search-button').click()};$('#prev-page').onclick=()=>{if(page>1){page--;browse()}};$('#next-page').onclick=()=>{page++;browse()};$('#refresh-button').onclick=()=>loadCategories();$('#launch-button').onclick=async()=>{try{const r=await call('launch');if(r?.message)notice(r.message)}catch{}};$('#import-button').onclick=()=>chooseCharacter('导入本地模组',async c=>{try{await call('import',c,{reload:true});notice('本地模组导入完成。')}catch{}});$('#save-preset-button').onclick=savePreset;$('#choose-xxmi').onclick=()=>mutate('chooseXXMI');$('#choose-mods').onclick=()=>mutate('chooseMods');$('#setup-xxmi').onclick=()=>mutate('setupXXMI');$('#detect-mods').onclick=()=>mutate('detectMods');$('#configure-xxmi').onclick=async()=>{try{const r=await call('configureXXMI');if(r?.message)notice(r.message)}catch{}};$('#open-data').onclick=()=>call('openData').catch(()=>{});$('#check-updates').onclick=checkUpdates;$('#check-updates-library').onclick=checkUpdates;const disableAll=()=>mutate('disableAll');$('#disable-all-library').onclick=disableAll;$('#disable-all-settings').onclick=disableAll;$('#auto-enable').onchange=e=>mutate('settings',{autoEnable:e.target.checked});$('#auto-update').onchange=e=>mutate('settings',{autoUpdate:e.target.checked});
api?.onProgress?.(p=>{const box=$('#progress'),bar=$('#progress-bar'),revision=++progressRevision;if(!p?.label){box.hidden=true;return}box.hidden=false;$('#progress-label').textContent=p.label;const total=Number(p.total)||0,received=Number(p.received)||0;bar.max=total||1;bar.removeAttribute('value');if(total){bar.value=received;$('#progress-value').textContent=Math.min(100,Math.round(received/total*100))+'%'}else $('#progress-value').textContent=formatSize(received);if(total&&received>=total)setTimeout(()=>{if(progressRevision===revision)box.hidden=true},1200)});api?.onState?.(snapshot=>{state=snapshot;renderState()});api?.onNotice?.(message=>{if(message)notice(message)});
(async()=>{try{await loadState();await loadCategories()}catch(e){notice(e?.message||'初始化失败，请重新启动应用。',true)}})();
