// Run with PLAYWRIGHT_MODULE pointing to an installed playwright package when it is not local.
const {_electron}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs/promises');
const path=require('node:path');
const os=require('node:os');
const assert=require('node:assert/strict');
const {Library}=require('../src/core/library.cjs');
(async()=>{
  const data=await fs.mkdtemp(path.join(os.tmpdir(),'hoyo-desktop-'));
  const input=path.join(data,'sample');await fs.mkdir(input);await fs.writeFile(path.join(input,'sample.ini'),'[Constants]\n$hat = 0\n[KeyHat]\nkey = H\nback = SHIFT H\ntype = cycle\n$hat = 0, 1\n[TextureOverrideBody]\nhash = aabbccdd\n');
  const lib=new Library(data);await lib.init();
  const a=await lib.install(input,{name:'本地样例 A',characterId:'18959',characterName:'Mona'});
  const b=await lib.install(input,{name:'本地样例 B',characterId:'18959',characterName:'Mona'});
  const modsPath=path.join(data,'GIMI','Mods');await fs.mkdir(modsPath,{recursive:true});await fs.writeFile(path.join(path.dirname(modsPath),'d3dx.ini'),'[Include]');
  await fs.writeFile(path.join(data,'taxonomy.json'),JSON.stringify([{id:17510,name:'Skins',children:[{id:18140,name:'Characters',children:[{id:18959,name:'Mona',children:[]}]}]}]));
  const packaged=process.env.HOYOMOD_PACKAGED;
  const app=await _electron.launch({executablePath:packaged||require('electron'),args:packaged?[]:[path.resolve(__dirname,'..')],env:{...process.env,HOYOMOD_DATA:data},timeout:30000});
  try {
    const page=await app.firstWindow();
    const gotoPage=async name=>{const t=page.locator(`[data-page="${name}"]:visible`).first();if(await t.count())return t.click();await page.evaluate(n=>showPage(n),name)};
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.waitForFunction(()=>!!window.hoyo);
    const snap=await page.evaluate(()=>window.hoyo.call('state'));
    assert.equal(snap.mods.length,2);
    await assert.rejects(page.evaluate(()=>window.hoyo.call('install',{sourceId:710045,fileId:1798090,characterId:'19498',characterName:'Raiden'})),/GIMI/);
    assert.deepEqual(snap.mods[0].hotkeys.bindings[0].keys,['H']);
    await gotoPage('library');
    await page.locator('.category').first().waitFor({state:'attached',timeout:45000});
    await page.locator('.folder-card').filter({hasText:'Skins'}).click();
    await page.locator('.folder-card').filter({hasText:'Characters'}).click();
    await page.locator('.folder-card').filter({hasText:'Mona'}).click();
    await page.locator('.hotkeys').first().click({timeout:40000});
    await page.locator('.hotkey-entry').waitFor();
    assert.match(await page.locator('#modal-body').textContent(),/KeyHat/);
    assert.deepEqual(await page.locator('.hotkey-entry kbd').allTextContents(),['H','SHIFT H']);
    assert.equal(await page.locator('#modal-body input, #modal-body textarea').count(),0);
    await page.locator('#modal-actions button').click();
    await page.locator('#replace-hash').click();
    await page.locator('#old-hash').fill('aabbccdd');await page.locator('#new-hash').fill('11223344');
    await page.locator('#preview-hash').click();await page.locator('#apply-hash').waitFor();
    assert.match(await page.locator('#modal-body').textContent(),/2 个模组、2 个文件、2 处匹配/);
    await page.locator('#apply-hash').click();
    await page.waitForFunction(async()=>((await window.hoyo.call('state')).hashBatches||[]).length===1);
    await page.locator('#hash-history').click();await page.locator('.rollback-hash').click();
    await page.locator('#confirm-rollback-hash').click();
    await page.waitForFunction(async()=>(await window.hoyo.call('state')).hashBatches[0].status==='rolledBack');
    await page.waitForFunction(()=>document.querySelector('#modal-title').textContent==='Hash 替换记录'&&document.querySelector('#modal').open);
    await page.locator('#modal-actions button').click();
    await page.evaluate(id=>window.hoyo.call('enable',{id}),a.id);
    await page.evaluate(id=>window.hoyo.call('enable',{id}),b.id);
    let actual=await page.evaluate(()=>window.hoyo.call('state'));
    assert.deepEqual(actual.mods.filter(m=>m.active).map(m=>m.id),[b.id]);
    await page.evaluate(()=>window.hoyo.call('savePreset',{name:'桌面验收方案'}));
    await page.evaluate(()=>window.hoyo.call('disableAll'));
    actual=await page.evaluate(()=>window.hoyo.call('state'));
    await page.evaluate(id=>window.hoyo.call('applyPreset',{id}),actual.presets[0].id);
    await page.evaluate(()=>window.hoyo.call('settings',{autoEnable:true,autoCheckUpdates:true,blurNsfw:false}));
    actual=await page.evaluate(()=>window.hoyo.call('state'));
    assert.equal(actual.settings.autoCheckUpdates,true);
    assert.equal(actual.mods.find(m=>m.id===b.id).active,true);
    await gotoPage('settings');
    await page.locator('#page-settings').waitFor({state:'visible'});
    const out=path.resolve(__dirname,'../test-results');await fs.mkdir(out,{recursive:true});
    await page.screenshot({path:path.join(out,'settings.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({passed:true,checks:['real Electron IPC','same-character replacement','presets','settings','settings UI'],screenshot:path.join(out,'settings.png')}));
  }finally{await app.close();await fs.rm(data,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
